language: cpp

compiler:
 - clang
 - gcc

before_install:
 - sudo apt-get update -y

install:
 - sudo apt-get -y install build-essential make

before_script:
 - sudo apt-get -y install libmapnik2-2.0 libmapnik-dev mapnik-utils

script:
 # workaround https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=63403 and https://bugs.launchpad.net/ubuntu/+source/cairomm/+bug/452733
 - export CXXFLAGS="-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include/"
 - make test/c-api-test && ./test/c-api-test
 - make test/c-api-c99-test && ./test/c-api-c99-test
